---
title: 'Course Project #2'
author: "Hayden Roche"
date: "November 21, 2017"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r loadstuff, include=FALSE}
library(magrittr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(png)
```

## Question 1: Early Data Manipulation: total emissions from all sources grouped by year

```{r q1}
setwd("/Users/hroche/Coursera/Coursera/")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI <- data.frame(NEI)
AggregTotals <- aggregate(Emissions ~ year, NEI, FUN = sum)
barplot((AggregTotals$Emissions)/10^6, names.arg = AggregTotals$year, main = "Total PM2.5 Emissions Over Time", xlab = "Year", ylab = "PM2.5 Emissions (in millions of tons)")
```


## Question 2: Baltimore City Maryland Emissions

```{r q2}
Baltimore_Data <- filter(NEI, fips == "24510")
Clean_SCC <- select(SCC, SCC, SCC.Level.One, SCC.Level.Two)
First_Data <- merge(Baltimore_Data, Clean_SCC, by = "SCC") %>%
  group_by(year) %>%
  summarise(sum(Emissions))

barplot(
  First_Data$`sum(Emissions)`, 
  names.arg = First_Data$year,
  main = "City of Baltimore: Historical Emission Trends",
  xlab = "Year",
  ylab = "PM2.5 Emissions (in tons)"
)
```

## Question 3: Emissions by Type Using GGPlot2

```{r q3}
Baltimore_Data <- filter(NEI, fips == "24510")

ggplot(Baltimore_Data, aes(x=factor(year), y=Emissions, fill=type,label = round(Emissions,2))) +
  geom_bar(stat="identity") +
  facet_grid(. ~ type) +
  xlab("year") +
  labs(title = "Emissions Trends by Type", subtitle = "NonPoint has seen the most drastic decrease in emissions")

```


## Question 4: Coal Combustion-Related Sources Over Time

```{r q4}
combustiononly <- grepl("comb", SCC$SCC.Level.One, ignore.case=TRUE)
coalonly <- grepl("coal", SCC$SCC.Level.Four, ignore.case=TRUE) 
Combustion_Coal <- (combustiononly & coalonly)
CombustionID <- SCC[Combustion_Coal,]$SCC
Final_Combustion <- NEI[NEI$SCC %in% CombustionID,]

Graph <- Final_Combustion %>%
  group_by(year) %>%
  summarise(sum(Emissions))
names(Graph)[names(Graph)=='sum(Emissions)'] <- "TotalEmissions"
ggplot(data = Graph, aes(x=(year), y = (TotalEmissions)/10^5)) +
  geom_bar(stat = "identity", fill = "orange") +
  theme_bw() +
  labs(x="Year", y = "Total Emissions (100,000s)") +
  labs(title = "Emissions from Coal-Combustion Sources")

```

## Question 5: Motor Vehicle Emissions in Baltimore

```{r q5}
vehicle_emissions <- grepl("vehicle", SCC$SCC.Level.Two, ignore.case = TRUE) 
vehicles2 <- SCC[vehicle_emissions,]$SCC 
vehicles3 <- NEI[NEI$SCC %in% vehicles2,]
Baltimore_cars <- filter(vehicles3, fips == "24510") 

Graph2 <- Baltimore_cars %>%
  group_by(year) %>%
  summarise(sum(Emissions))
names(Graph2)[names(Graph2)=='sum(Emissions)'] <- "TotalEmissions"
ggplot(data = Graph2, aes(x=(year), y = TotalEmissions)) +
  geom_bar(stat="identity",fill="purple") +
  theme_bw() +
  labs(x="Year", y="Emissions (in Tons)") +
  labs(title = "Motor Vehicle Emissions in Baltimore, MD")

```

## Question 6: Motor Vehicle Emissions in Baltimore vs. Los Angeles

```{r q6}
vehicle_emissions <- grepl("vehicle", SCC$SCC.Level.Two, ignore.case = TRUE) 
vehicles2 <- SCC[vehicle_emissions,]$SCC 
vehicles3 <- NEI[NEI$SCC %in% vehicles2,]

Baltimore_cars <- filter(vehicles3, fips == "24510") 
LA_cars <- filter(vehicles3, fips == "06037")
Mix_Data <- rbind(Baltimore_cars, LA_cars)

Graph3 <- Mix_Data %>%
  group_by(year, fips) %>%
  summarise(sum(Emissions))
names(Graph3)[names(Graph3)=='sum(Emissions)'] <- "TotalEmissions"
ggplot(data = Graph3, aes(x=(year), y = (TotalEmissions))) +
  geom_bar(aes(fill=fips), stat = "identity") +
  facet_grid(scales = "free", space = "free", .~fips) +
  guides(fill=FALSE) +
  theme_bw() +
  labs(x="Year", y="Total Vehicle Emissions") +
  labs(title="Motor Vehicle Emissions in Baltimore, MD versus Los Angeles, CA")

```

